# Default values for rsstodiscord.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: cromrots/rsstodiscord
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

configuration:
  - name: DISCORD_WEBHOOK
    valueFrom:
      secretKeyRef:
        name: rsstodiscord
        key: discord_webhook
  - name: RSS_URL
    valueFrom:
      secretKeyRef:
        name: rsstodiscord
        key: rss_url
  # - name: INTERVAL
  #   value: 5m
  # - name: REDIS_ADDRESS
  #   value: host:port
  # - name: REDIS_PASSWORD
  #   valueFrom:
  #     secretKeyRef:
  #       name: rsstodiscord
  #       key: redis_password
  # - name: REDIS_DATABASE
  #   value: "0"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 20Mi
  # requests:
  #   cpu: 100m
  #   memory: 20Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
